// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEiZwF1bqedhAYNaSy4cOCdY3EU0sHCH4',
    appId: '1:563779169223:web:995c2132721c76c21a87e2',
    messagingSenderId: '563779169223',
    projectId: 'crud-app-87e52',
    authDomain: 'crud-app-87e52.firebaseapp.com',
    storageBucket: 'crud-app-87e52.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGYg6OaoOLo3CVjcRmveKdQ99Z6X-Pe_k',
    appId: '1:563779169223:android:c791befc369682a51a87e2',
    messagingSenderId: '563779169223',
    projectId: 'crud-app-87e52',
    storageBucket: 'crud-app-87e52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKp4W5Rp9p2VRkjiDb-l21EjTUIg1lMQA',
    appId: '1:563779169223:ios:20d6c2b1787292ce1a87e2',
    messagingSenderId: '563779169223',
    projectId: 'crud-app-87e52',
    storageBucket: 'crud-app-87e52.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKp4W5Rp9p2VRkjiDb-l21EjTUIg1lMQA',
    appId: '1:563779169223:ios:20d6c2b1787292ce1a87e2',
    messagingSenderId: '563779169223',
    projectId: 'crud-app-87e52',
    storageBucket: 'crud-app-87e52.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEiZwF1bqedhAYNaSy4cOCdY3EU0sHCH4',
    appId: '1:563779169223:web:712e665d39eeec361a87e2',
    messagingSenderId: '563779169223',
    projectId: 'crud-app-87e52',
    authDomain: 'crud-app-87e52.firebaseapp.com',
    storageBucket: 'crud-app-87e52.firebasestorage.app',
  );
}
